CONFIG_ZMK_KEYBOARD_NAME="roBa ESB"

CONFIG_ZMK_MOUSE=y
CONFIG_ZMK_POINTING=y
CONFIG_ZMK_USB=y
CONFIG_INPUT=y
CONFIG_GPIO=y
CONFIG_ROBA_DESKHOP_LAYER_SYNC=y
CONFIG_ROBA_DESKHOP_LAYER_SYNC_LED_MASK=0x01
CONFIG_ROBA_DESKHOP_LAYER_WHEN_LED_ON=1
CONFIG_ROBA_DESKHOP_LAYER_WHEN_LED_OFF=0
CONFIG_ZMK_DESKHOP_SYNC_REPORT=y
CONFIG_ZMK_DESKHOP_SYNC_REPORT_ID=0x7E
CONFIG_ZMK_DESKHOP_SYNC_LAYER_A=0
CONFIG_ZMK_DESKHOP_SYNC_LAYER_B=1

CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=n

CONFIG_ZMK_BLE=n
CONFIG_ZMK_SPLIT_BLE=n
CONFIG_ZMK_SPLIT_WIRED=n
CONFIG_ZMK_SPLIT_ESB=y
CONFIG_ZMK_SPLIT_ESB_PROTO_MSGQ_ITEMS=64
CONFIG_ZMK_SPLIT_ESB_EVENT_BUFFER_ITEMS=64
CONFIG_ZMK_SPLIT_ESB_CMD_BUFFER_ITEMS=16
CONFIG_ZMK_SPLIT_ESB_PROTO_TX_RETRANSMIT_COUNT=3
CONFIG_ZMK_SPLIT_ESB_PROTO_TX_RETRANSMIT_DELAY=600

CONFIG_MPSL_TIMESLOT_SESSION_COUNT=1
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=4096
CONFIG_ESB_MAX_PAYLOAD_LENGTH=48
CONFIG_ESB_TX_FIFO_SIZE=1
CONFIG_CRC=y

CONFIG_ZMK_BATTERY_REPORTING=y

CONFIG_INPUT_THREAD_STACK_SIZE=8192
CONFIG_INPUT_QUEUE_MAX_MSGS=512

CONFIG_ZMK_POINTING_SMOOTH_SCROLLING=n

CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_BLANK_ON_IDLE=y
CONFIG_ZMK_IDLE_TIMEOUT=300000
CONFIG_DISPLAY_INIT_PRIORITY=95

CONFIG_ZMK_DONGLE_DISPLAY_BONGO_CAT=n
CONFIG_ZMK_DONGLE_DISPLAY_MODIFIERS=n
CONFIG_ZMK_DONGLE_DISPLAY_LAYER_NAME_SCROLL_WIDTH=90
CONFIG_ZMK_DONGLE_DISPLAY_LAYER_TEXT_ALIGN="left"
CONFIG_ZMK_DONGLE_DISPLAY_LAYER_ALIGN_LEFT=y
CONFIG_ZMK_DONGLE_DISPLAY_DONGLE_BATTERY=n

CONFIG_ZMK_DISPLAY_DEDICATED_THREAD_STACK_SIZE=8192
CONFIG_LV_Z_MEM_POOL_SIZE=16384
