file_format: "1"
id: charybdis_dongle
name: Charybdis Dongle
type: shield
url: https://github.com/Bastardkb/Charybdis/
requires: [pro_micro]
features:
  - keys
  - pointer
siblings:
  - charybdis_dongle
  - charybdis_dongle_left
  - charybdis_dongle_right
