CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
CONFIG_ZMK_HID_INDICATORS=y
CONFIG_ROBA_DESKHOP_LAYER_SYNC=y
CONFIG_ROBA_DESKHOP_LAYER_SYNC_LED_MASK=0x01
CONFIG_ROBA_DESKHOP_LAYER_WHEN_LED_ON=1
CONFIG_ROBA_DESKHOP_LAYER_WHEN_LED_OFF=0
