manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: charlesmst
      url-base: https://github.com/charlesmst
    - name: damex
      url-base: https://github.com/damex
    - name: nrfconnect
      url-base: https://github.com/nrfconnect
    - name: urob
      url-base: https://github.com/urob

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml

    - name: zmk-pmw3610-driver
      remote: charlesmst
      repo-path: zmk-pmw3610-driver-efog
      revision: zmk0.4

    - name: zmk-input-processor-accel
      remote: charlesmst
      revision: main

    - name: zmk-tri-state
      path: modules/zmk/tri-state
      remote: urob
      revision: main

    - name: zmk-feature-split-esb
      remote: damex
      revision: pass-battery-events-for-esb-only-central
      import: true

  self:
    path: config
