CONFIG_ZMK_KEYBOARD_NAME="roBa KESB"

# USB dongle — no BLE to host
CONFIG_ZMK_USB=y
CONFIG_ZMK_BLE=n
CONFIG_ZMK_SPLIT_BLE=n
CONFIG_ZMK_SPLIT_WIRED=n

# kumbung01 ESB central
CONFIG_ZMK_SPLIT_ESB=y
CONFIG_CLOCK_CONTROL_NRF_K32SRC_XTAL=y
CONFIG_ESB_MAX_PAYLOAD_LENGTH=48
CONFIG_ESB_TX_RINGBUF=y
CONFIG_ESB_RX_FIFO_SIZE=32

# Two peripherals (left + right)
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y

# Mouse / trackball via split
CONFIG_ZMK_MOUSE=y
CONFIG_ZMK_POINTING=y
CONFIG_INPUT=y
CONFIG_GPIO=y

CONFIG_ZMK_HID_CONSUMER_REPORT_USAGES_FULL=y
CONFIG_ZMK_HID_INDICATORS=y
CONFIG_ZMK_BEHAVIORS_QUEUE_SIZE=512

# Logging
CONFIG_ZMK_SPLIT_ESB_LOG_LEVEL_DBG=y
CONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=8000
