file_format: "1"
id: roBakesb
name: roBakesb (kumbung01 ESB)
type: shield
url: https://github.com/charlesmst/zmk-config-generic
requires: [pro_micro]
features:
  - keys
  - pointer
siblings:
  - roBakesb
  - roBakesb_left
  - roBakesb_right
