CONFIG_ZMK_KEYBOARD_NAME="roBa KESB R"

CONFIG_ZMK_BLE=n
CONFIG_ZMK_SPLIT_BLE=n
CONFIG_ZMK_SPLIT_WIRED=n

# kumbung01 ESB peripheral, ID 1 = right (with trackball)
CONFIG_ZMK_SPLIT_ESB=y
CONFIG_ZMK_SPLIT_ESB_PERIPHERAL_ID=1

CONFIG_CLOCK_CONTROL_NRF_K32SRC_RC=y
CONFIG_ESB_MAX_PAYLOAD_LENGTH=48
CONFIG_ESB_TX_RINGBUF=y
CONFIG_ESB_TX_RINGBUF_SIZE=400

CONFIG_ZMK_MOUSE=y
CONFIG_ZMK_POINTING=y
CONFIG_INPUT=y
CONFIG_GPIO=y
CONFIG_SPI=y
CONFIG_NFCT_PINS_AS_GPIOS=y

# PMW3610 trackball
CONFIG_PMW3610=y
CONFIG_PMW3610_OUTPUT_RATE_NOTIFY=y
CONFIG_PMW3610_LOG_LEVEL_DBG=y
CONFIG_PMW3610_SQUAL_LOG=y
CONFIG_PMW3610_SQUAL_LOG_INTERVAL=500
CONFIG_PMW3610_RUN_DOWNSHIFT_TIME_MS=3264
CONFIG_PMW3610_REST1_SAMPLE_TIME_MS=20

CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000

CONFIG_ZMK_BATTERY=y
CONFIG_ZMK_BATTERY_REPORTING=y

CONFIG_NEWLIB_LIBC=y
CONFIG_COMPILER_OPT="-D_RETARGETABLE_LOCKING"

CONFIG_INPUT_THREAD_STACK_SIZE=8192
CONFIG_INPUT_QUEUE_MAX_MSGS=512

CONFIG_ZMK_SPLIT_ESB_LOG_LEVEL_DBG=y
